<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MGTECHLPT311" failures="0" tests="4" name="TestClass.TC_001_IndexPage_Test" time="0.000" errors="1" timestamp="2023-07-17T11:04:56 IST" skipped="3">
  <testcase classname="TestClass.TC_001_IndexPage_Test" name="setUp" time="0.000">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at TestBase.BaseClass.Launch_Application(BaseClass.java:55)
at TestClass.TC_001_IndexPage_Test.setUp(TC_001_IndexPage_Test.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase classname="TestClass.TC_001_IndexPage_Test" name="LogoTest" time="0.000">
    <skipped/>
  </testcase> <!-- LogoTest -->
  <system-out/>
  <testcase classname="TestClass.TC_001_IndexPage_Test" name="TitleTest" time="0.000">
    <skipped/>
  </testcase> <!-- TitleTest -->
  <system-out/>
  <testcase classname="TestClass.TC_001_IndexPage_Test" name="AccountSetuptest" time="0.000">
    <skipped/>
  </testcase> <!-- AccountSetuptest -->
  <system-out/>
</testsuite> <!-- TestClass.TC_001_IndexPage_Test -->
